### ISSUE TITLE
Trains no longer run

### ISSUE THREAD

**Issue by mldulaney** [orwell96/advtrains#100]
Updated the server to 0.4.16, and trains no longer run.  When I hit w, for instance, I just walk off.

**Comment by gpcf** [comment]
John Dulaney <notifications@github.com> writes:

> Updated the server to 0.4.16, and trains no longer run. When I hit w, for instance, I just walk off.
You need to get on to the driver seat before being able to drive a
train. You do this by right-clicking.

**Comment by gpcf** [comment]
Please close

**Comment by mldulaney** [comment]
I am, in fact, in the drivers seat.

**Comment by orwell96** [comment]
ah. this means you don't have the train_operator privilege
You need to execute the command
/grantme train_operator
I introduced this privilege to protect against griefers on public servers.

**Comment by orwell96** [comment]
I consider this solved
