### ISSUE TITLE
Incorrect slash

### ISSUE THREAD

**Issue by kostett** [orwell96/advtrains#107]
https://github.com/orwell96/advtrains/blob/7507dbba3ae566a6175ad0f63bb599144534e4ee/advtrains/nodedb.lua#L55
When run mod on Windows, ndb doesn't saving after server shutdown and on the next run of the server with advtrains all the advtrains nodes rotated randomly.

**Comment by orwell96** [comment]
Ah. that's the reason for this...
Thanks very much for reporting. I've always wondered why saving the node db is so buggy on windows

**Comment by kostett** [comment]
Thanks for fixing.
https://github.com/orwell96/advtrains/commit/27afd89d1b337fe4a4d34f2184f4838c2c8722c1

**Comment by rubenwardy** [comment]
Lua automatically handles this for you (converting / to \ on Windows). This fix isn't needed

**Comment by orwell96** [comment]
Well, at least it's consistent now

**Comment by kostett** [comment]
This "automatically handle" works not everywhere. Screen from another mod, but error is same.
![photo_2018-01-18_21-13-41](https://user-images.githubusercontent.com/3895729/35114092-8386853c-fc7b-11e7-91e1-1a88cc6625a3.jpg)
Maybe there is buggy build for Windows, I don't know.
