### ISSUE TITLE
Crash when force-joining a turning train

### ISSUE THREAD

**Issue by nanepiwo** [orwell96/advtrains#110]
Attempt to perform arithmetic on a nil value at https://github.com/orwell96/advtrains/blob/master/advtrains/wagons.lua#L529 (I think because yaw is nil?) 

Note that the infotext displayed when riding a train does appear, and persists, to the player who tries to join the turning train

**Comment by orwell96** [comment]
Self.player_yaw is nil
fixing...

**Comment by orwell96** [comment]
Should be fixed now
