### ISSUE TITLE
On-board computer access is restricted by privilege, and not accessible to "mere" owners.

### ISSUE THREAD

**Issue by h-v-smacker** [orwell96/advtrains#111]
The way it currently works, people who can drive their trains still can be barred from using the on-board computers because the access to them is restricted to those with "train_operator" privilege.

**Comment by orwell96** [comment]
I'll need to rework the whole privilege system anyway. But thanks for reporting!

**Comment by h-v-smacker** [comment]
Speaking of privileges, yesterday we found out that the freight wagons are not protected: anybody can place things inside and take them out, regardless of ownership or even train_operator privilege. On the other hand, only privileged players can couple and decouple trains...

**Comment by orwell96** [comment]
Oh, right, the freight Wagons are still not protected
The Rest should work now.
