### ISSUE TITLE
Switching rails error

### ISSUE THREAD

**Issue by codexp** [orwell96/advtrains#113]
Switching rails have no effect on first pass, only on second pass train goes to different track.

I have a setup of a round course with lua controller switching tracks to three train garages.
Trains go for a drive over the course one by one.
Once a train has made a round, it stops and reverses back to it's garage.
Track is switched by lua controller even before train passes it (in previous version they have been switched after train has passed it).
Then when train reverses, track switch should direct the train to pointed direction, **but it does not**.
So train passes the switch and goes not where that switch is set to, makes a full round and then makes the right turn (without switch being modified or re-switched again).

I could not figure out, why train has to pass a switch twice to take the direction the switch is set to.
It seems like a bug with switches (maybe because of the train going in reverse?).

**Comment by codexp** [comment]
![screenshot_20180428_004258](https://user-images.githubusercontent.com/6502486/39388270-08cd4fae-4a7f-11e8-98f0-7434e8603b4f.png)

**Comment by codexp** [comment]
Btw SW1 works always on first pass!

**Comment by orwell96** [comment]
I know this problem, this is due to some internal mechanics. The train's path (the track it runs along) doesn't get updated when the train reverses, but it does when a turnout is switched.
(it would work when you switch the turnout back and forth after the train passed it)
I recently reworked a lot of code around the path system, which also fixes this bug.

**Comment by codexp** [comment]
nice to hear that, when can we expect a release?

**Comment by codexp** [comment]
I also noticed that if the reverse path is long enough (maybe > 15 blocks) this also works fine, but does not work for trains that change direction too early. Manual switching the rails helps too (but not a solution).

I should try switching back and forth again, after train passes a switch (last time I tried, it did not help).

**Comment by orwell96** [comment]
2 weeks...
right, because the train clears the path once far enough away.

**Comment by codexp** [comment]
Switching back and forth has helped.

**Comment by orwell96** [comment]
fixed in tss branch

**Comment by codexp** [comment]
what is this tss branch and when will it be merged to master?

**Comment by orwell96** [comment]
It's the branch where I am implementing the interlocking system. Merge to master probably somewhen around September
