### ISSUE TITLE
pitch wagons on slopes

### ISSUE THREAD

**Issue by orwell96** [orwell96/advtrains#119]
https://github.com/minetest/minetest/pull/7331
When this gets merged, I'll add code to use it if it's available

**Comment by gpcf** [comment]
Wonderful!

**Comment by ghost** [comment]
By the way, a different PR of mine was merged that adds set_rotation(). Pitching trains will probably work now.

**Comment by orwell96** [comment]
Oh, right. I've integrated it, it works.
I don't really pay attention to issues on GitHub, since the official bug tracker is hemiptera
