### ISSUE TITLE
Bug when dying while riding train - And: Leaving game while on train!

### ISSUE THREAD

**Issue by Thomas--S** [orwell96/advtrains#12]
When the player dies while riding the industrial train, the mod behaves very buggy.

**Comment by Desour** [comment]
what happens exactly:question:

**Comment by Thomas--S** [comment]
I didn't do further testing, but it seems like you are still registered as train driver, but you can't unmount anymore.

**Comment by gpcf** [comment]
Can confirm. Exactly that happens, not only on the industrial train, but also on the steam train.

**Comment by orwell96** [comment]
You should just get re-attached to it when you come near!?!
I dont have time now.

**Comment by Thomas--S** [comment]
@orwell96 I think it would be better to get properly de-attached.

**Comment by orwell96** [comment]
Right. But it does not take care about death yet, the reattachment is for players re-joining the game

**Comment by gpcf** [comment]
The problem is that you seem to die after reaching a certain speed. I just did some testing and it happens with the industrial train, but has also happened with the steam train.

**Comment by gpcf** [comment]
I think this is closed.

**Comment by orwell96** [comment]
no, it is not. i need to investigate this problem.
remains open until i implemented proper behavior for this case

**Comment by gpcf** [comment]
Did you turn off damage in train crashes? Because I do not die now while riding the trains.

**Comment by orwell96** [comment]
No, i just fixed code that was supposed to work but did not.
You die when you get overrun by a train(not only the wagon) you do not sit on.

**Comment by orwell96** [comment]
Issue: when you leave game while on a train and the train moves away, you will be dropped on the rails but are reattached to train as soon as it gets loaded again - which doesn't prevent you to go on another train meanwhile, leading to sitting in 2 trains at the same time -> not good.
