### ISSUE TITLE
Wagon is full when it's empty

### ISSUE THREAD

**Issue by codexp** [orwell96/advtrains#123]
I get an error message: Can't get on: wagon is full. 
when I tried to enter the train through platform, but train was empty.

**Comment by codexp** [comment]
btw this is 123 ticket, so should be easy to fix ;)

**Comment by orwell96** [comment]
Are you playing on a server? There, offline players also occupy seats and are placed in the train again when they come online

**Comment by codexp** [comment]
Yes, I play on a public server. 
Oh I see, but I doubt the train is full with (regular) offline players, since I saw most of them playing somewhere. So it is probably full of visitor noobs, who have never managed to come off the train and left the game, perhaps for ever.

I saw a command to kick all passengers out of train.

So one could use this command if server is empty (all/most clients offline)?

`/at_empty_seats` - Detach all players, especially the offline ones, from all trains. Use only when no one serious is on a train.

**Comment by codexp** [comment]
Is it possible to send offline players after a time threshold (maybe 48 hours) to their home position?

**Comment by orwell96** [comment]
Would be possible, but difficult to implement

**Comment by orwell96** [comment]
maybe set them off when the train stops the next time (e.g. opens its doors)

**Comment by codexp** [comment]
yes I thought of that too.

If you think of real life example, you have to get off at the end station (whether you want or not).
Which would be hard to determine (which one is the end station?).

But as a trade off, this would be a good solution, to set them off at any station after doors get open.

Maybe one condition for setting offline passengers off: offline >1h (if that is possible)
