### ISSUE TITLE
New Idea : A mesecon start/stop rail

### ISSUE THREAD

**Issue by Emojigit** [orwell96/advtrains#128]
I think this mod need to add a mesecon start/stop rail that will stop ATC trains when no signal, and resume ATC train's speed when have signal.

That rail will not affect Manual trains.

**Comment by Montandalar** [comment]
Hi, this issue section is no longer active, you should post your idea to the [bugtracker](http://bugs.linux-forks.de/advtrains/) by email (advtrains@bugs.linux-forks.de)

**Comment by Emojigit** [comment]
Thank you
