### ISSUE TITLE
idea: track ownership

### ISSUE THREAD

**Issue by ValkyrieStella** [orwell96/advtrains#21]
when laying miles of track, especially when it curves, protecting track is a pain. What if tracks acted like steel doors: only the person who laid the track (or admins) could remove them? would prevent griefing of umprotected tracks. this would be much easier. @orwell96  @gpcf

**Comment by gpcf** [comment]
It should add a 3x3x3 box around the track that is protected. I will implement this as soon as I have time, this is not really hard to do. The biggest problem I see is that you want to join railways by different players. I may solve this by rather writing this as addition to areas, so areas overrides the default protection.

**Comment by ValkyrieStella** [comment]
@gpcf  at that rate i may as well lay a protection block, but it is easier to have tracks that protect themselves

@orwell96  here is a modification to my idea. maybe instead of changing current dtracks you should just add tracks. as there are unlocked doors and locked doors in the doors mod, you should have locked tracks and unlocked tracks.

**Comment by orwell96** [comment]
The thing I dislike about this is that we would have MASSES of node metadata about who owns the tracks.
I think it's best if you add protection labels ('protector' mod) in regular intervals, on Cashs World all roads are only protected by these protection markers.

**Comment by orwell96** [comment]
more or less achieved by the new privilege system
