### ISSUE TITLE
sneak instead of shift

### ISSUE THREAD

**Issue by ValkyrieStella** [orwell96/advtrains#24]
saying shift instead of sneak can be confusing for both the force-on when doors are closed as well as the force-break the train. first of all sneak by default is left shift, also many people are on mobile and dont have shift but sneak button. also, on computer, many people change the default.

**Comment by gpcf** [comment]
Compromise solution: sneak (shift)

**Comment by gbl08ma** [comment]
Just talking out of my head, but is there an API for mods to read the currently assigned keymap? That way this mod could read the name of the key and display "sneak ([appropriate key name here])". Still wouldn't make much sense on mobile, and I doubt such an API call exists, going to check now.

**Comment by ValkyrieStella** [comment]
@gpcf  what if people do a right shift then?

**Comment by orwell96** [comment]
To Do.
