### ISSUE TITLE
Document how to rotate ATC rails

### ISSUE THREAD

**Issue by gbl08ma** [orwell96/advtrains#25]
Is it just me, or ATC rails can't be rotated? In some cases, when placing them on an existing track, they'll have the wrong orientation. And I can't rotate them with the track worker tool (it just opens the formspec). Because they are rotated, the trains can't go through.

![screenshot_20170129_002944](https://cloud.githubusercontent.com/assets/984584/22400931/109c7f96-e5ba-11e6-8cca-62e74df81ef2.png)

Am I doing something wrong?

**Comment by ValkyrieStella** [comment]
oh its easy, you need to sneak+ left click

**Comment by ValkyrieStella** [comment]
that prevents a right click and acts like a normal right click. same way if you want to set a node on top of a thing that can be right clicked

**Comment by gbl08ma** [comment]
Thank you, I completely forgot one could do that.

Still, I think it would be more user-friendly if the track worker tool had priority over the formspec (since to open the formspec, one can always select any other item).

**Comment by ValkyrieStella** [comment]
no need

**Comment by orwell96** [comment]
I need to write that down in the manual somewhere

**Comment by gpcf** [comment]
Well, the trackworker gets special treatment when it comes to switches, so it should also rotate atc rails without using shift, but the best solution would be just making the atc rails align with the other rails.

**Comment by ValkyrieStella** [comment]
@gpcf  i dont see why it should need to rotate atc's without shift. totally unnecessary. everyone should know you use sneak to avoid function when right clicking. but yes it would also be nice to make them align with the other rails.

**Comment by orwell96** [comment]
Btw. engine currently does not even send the rightclick event to the server once a formspec is set for the node.

**Comment by gbl08ma** [comment]
That's a bit limiting, but just document the current behavior and call it a day.
