### ISSUE TITLE
subway

### ISSUE THREAD

**Issue by ValkyrieStella** [orwell96/advtrains#30]
should the subway be able to seat more people? would be a good idea..

**Comment by orwell96** [comment]
how many people do you want?

**Comment by ValkyrieStella** [comment]
maybe unlimited, or maybe like 5 or 10.

**Comment by orwell96** [comment]
There are 4 seats now. Every seat has its offset position. New positions can be defineds very easy, see subway init.lus

**Comment by ValkyrieStella** [comment]
ok

**Comment by gpcf** [comment]
I think this issue should be closed. 4 People is enough per car, if you have 3-car subways, you already have 12 seats per train, which is a lot.
