### ISSUE TITLE
Trains tend to get stuck in switches

### ISSUE THREAD

**Issue by gpcf** [orwell96/advtrains#61]
Subway lines on Linuxworks don't work any longer, the trains sometimes get stuck when passing a switch in the wrong direction.

**Comment by orwell96** [comment]
Old or new server?
That's right, they get stuck when passing in the wrong direction. But in the cases I ve seeon on the new linuxworks, all trains should never have departed

**Comment by gpcf** [comment]
New server, and the trains work normally, except where there are switches, even if they are in the right position.

**Comment by orwell96** [comment]
I think the issue you mean was the one i've fixed lately. If not, tell me
