### ISSUE TITLE
Undeclared Global Variables: "st", "increativeinv", & "switchfunc"

### ISSUE THREAD

**Issue by AntumDeluge** [orwell96/advtrains#68]
Getting the following warnings when running my server:

> 2017-05-13 13:14:54: WARNING[Main]: Undeclared global variable "st" accessed at ...mes/antum-testing/mods/mp_advtrains/advtrains/tracks.lua:157
> 2017-05-13 13:14:54: WARNING[Main]: Undeclared global variable "st" accessed at ...mes/antum-testing/mods/mp_advtrains/advtrains/tracks.lua:182
> 2017-05-13 13:14:54: WARNING[Main]: Undeclared global variable "increativeinv" accessed at ...mes/antum-testing/mods/mp_advtrains/advtrains/tracks.lua:313
> 2017-05-13 13:14:54: WARNING[Main]: Undeclared global variable "switchfunc" accessed at ...es/antum-testing/mods/mp_advtrains/advtrains/signals.lua:30
> 2017-05-13 13:14:54: WARNING[Main]: Undeclared global variable "switchfunc" accessed at ...es/antum-testing/mods/mp_advtrains/advtrains/signals.lua:65

advtrains build: [da884af][build.advtrains]
Minetest server build: [0d4d35a][build.minetest]
OS: Linux Mint 18.1 64-bit

[build.advtrains]: https://github.com/orwell96/advtrains/tree/da884af
[build.minetest]: https://github.com/minetest/minetest/tree/0d4d35a

**Comment by orwell96** [comment]
These are not dangerous. but I might fix them

**Comment by AntumDeluge** [comment]
Okay, just wanted to let you know. Didn't know if they were important or not.

**Comment by orwell96** [comment]
But thanks anyway, you are right, i should do this

**Comment by orwell96** [comment]
fixed
