### ISSUE TITLE
encountering error

### ISSUE THREAD

**Issue by ValkyrieStella** [orwell96/advtrains#69]
i have a single downhil slope that comes right before a station, however when i leave a train unattended it goes over the slope and hits the bumpers, not at all reading the atc tracks. downhill slope can be seen in https://snag.gy/aXVdeZ.jpg . this has happened in both japanese trains and normal subways. i dont understand what is happening. the train gets stuck as a result

**Comment by orwell96** [comment]
I can't see the image

**Comment by numberZero** [comment]
The image page is broken, but this seems to be its image:
![](https://i.snag.gy/aXVdeZ.jpg)

**Comment by gpcf** [comment]
this is a problem with the digtron not calling at_restore_ndb. Were you placing advtrains:dtrack_st or advtrains:dtrack_placer objects?

**Comment by orwell96** [comment]
Wait, this construction is on the linuxworks server, right?
Can you give me the coordinates?

**Comment by gpcf** [comment]
orwell96 writes:

> Wait, this construction is on the linuxworks server, right?
> Can you give me the coordinates?
I'm Currently there.

**Comment by orwell96** [comment]
seems to be fixed, if not, please reopen issue
