### ISSUE TITLE
many unneeded files

### ISSUE THREAD

**Issue by Desour** [orwell96/advtrains#7]
normally Minetest mods are much smaller. this one takes more than 50 Megabytes
one reason for this are the extra saved .blend1 files. blender makes them automatically on saving. they should be deleted
edit: also some textures got much too high resolution

**Comment by orwell96** [comment]
right.

**Comment by orwell96** [comment]
I now removed all .blend and additional files from the repo. If someone needs them, ask me.
size is still about 13MB...
the manual is 1mb itself, textures folder another 10mb, the b3d files need only 2mb. rest are mostly the license files.

**Comment by gpcf** [comment]
I don't think you should remove all .blend files, rather you should have removed all .blend1 files. This repository is meant to be a source repo, and the .blend files are part of the source. In fact, you may even be required to do that by the LGPL license, but I'm not sure.

**Comment by gpcf** [comment]
also, there are two .xcf files in the textures that amount to ~9-10 MB together. I don't know whether they serve any function. Do you use them? If not, remove them. Also, I think it would be a good idea to outsource the manual to the website repo.

**Comment by orwell96** [comment]
goal is to decrease download size.
these blender folders do also include xcfs, these are huge. all models are included in the mod as b3d, so having them as .blend is not necessary from license's view. but I made them available here:
https://github.com/orwell96/advtrains_draft_content
xcfs moved too

**Comment by orwell96** [comment]
4.5MB
I'll leave the manual in

**Comment by gpcf** [comment]
How about compiling a .zip file with everything that's necessary for downloading? This can be done via a git post-upload hook. I don't know whether this can be done on github, but I can do this on my own server, so I could provide that zip file from my website if you want.

I think this repo should be here to contain absolutely everything needed to work on this project, not just the stuff to run it.

**Comment by Desour** [comment]
ok, now its 10% of the size that was before...
you should also scale down some textures. for example the signals even lag on diging them. 1024² is not needed.

**Comment by Desour** [comment]
oh, and for nodes use wavefront(.obj) model format, they need less disc space

**Comment by gpcf** [comment]
Oh, and remove all these old track textures and stuff, leave only dtrack there, since the old track was de-facto removed.

**Comment by orwell96** [comment]
The old track will get its renaissance with mine trains soon.

**Comment by gpcf** [comment]
Fixed this stuff, see #9. There is now a zip file living at https://en.gpcf.eu/advtrains.zip

**Comment by Desour** [comment]
oh, mine carts
ill try to make a nice model
